import { ThemeTokens } from '../models';

export type BuiltinThemeId =
  | 'neon'
  | 'pop'
  | 'forest'
  | 'arcade'
  | 'sakura'
  | 'shrine'
  | 'atlas'
  | 'scrapbook'
  | 'kiyo'
  | 'liquid'
  | 'wamon'
  | 'sumi'
  | 'kawaii'
  | 'izakaya'
  | 'zen';

export interface BuiltinThemePreset {
  id: BuiltinThemeId;
  name: string;
  tokens: ThemeTokens;
}

const DEFAULT_FONT = '"Segoe UI", system-ui, -apple-system, Roboto, sans-serif';

export const BUILTIN_THEME_PRESETS: readonly BuiltinThemePreset[] = [
  {
    id: 'neon',
    name: 'Neon Night',
    tokens: {
      primary: '#22d3ee',
      primaryInk: '#042f2e',
      accent: '#f472b6',
      bg: '#0c1222',
      surface: '#151d32',
      ink: '#e8f4ff',
      muted: '#7b8db5',
      line: '#243049',
      good: '#34d399',
      bad: '#fb7185',
      radius: '0.75rem',
      radiusLg: '1rem',
      shadow: '0 0 24px rgba(34, 211, 238, 0.12)',
      font: '"Space Grotesk", system-ui, sans-serif',
      fontDisplay: '"Syne", sans-serif',
    },
  },
  {
    id: 'pop',
    name: 'Bold Pop',
    tokens: {
      primary: '#db2777',
      primaryInk: '#ffffff',
      accent: '#7c3aed',
      bg: '#faf5ff',
      surface: '#ffffff',
      ink: '#1e1b2e',
      muted: '#6b5b7a',
      line: '#e9d5ff',
      good: '#059669',
      bad: '#e11d48',
      radius: '0.5rem',
      radiusLg: '0.75rem',
      shadow: '4px 4px 0 #1e1b2e',
      font: DEFAULT_FONT,
      fontDisplay: '"Syne", sans-serif',
    },
  },
  {
    id: 'forest',
    name: 'Forest Quest',
    tokens: {
      primary: '#166534',
      primaryInk: '#ecfdf5',
      accent: '#ca8a04',
      bg: '#f0fdf4',
      surface: '#ffffff',
      ink: '#14532d',
      muted: '#4d7c5e',
      line: '#bbf7d0',
      good: '#15803d',
      bad: '#b45309',
      radius: '1.5rem',
      radiusLg: '2rem',
      shadow: '0 3px 14px rgba(22, 101, 52, 0.12)',
      font: DEFAULT_FONT,
      fontDisplay: '"Outfit", sans-serif',
    },
  },
  {
    id: 'arcade',
    name: 'Electric Arcade',
    tokens: {
      primary: '#6366f1',
      primaryInk: '#ffffff',
      accent: '#f43f5e',
      bg: '#1e1b4b',
      surface: '#312e81',
      ink: '#e0e7ff',
      muted: '#a5b4fc',
      line: '#4338ca',
      good: '#4ade80',
      bad: '#fb7185',
      radius: '0.25rem',
      radiusLg: '0.5rem',
      shadow: '0 0 0 2px #f43f5e',
      font: '"Space Grotesk", monospace',
      fontDisplay: '"Syne", sans-serif',
    },
  },
  {
    id: 'sakura',
    name: 'Sakura Matsuri',
    tokens: {
      primary: '#3d4a6b',
      primaryInk: '#fffaf8',
      accent: '#d4789a',
      bg: '#faf6f1',
      surface: '#fffefb',
      ink: '#2a2438',
      muted: '#7a7089',
      line: '#e8d5dc',
      good: '#5a8f6a',
      bad: '#b84a5c',
      radius: '0.35rem',
      radiusLg: '0.5rem',
      shadow: '0 2px 10px rgba(61, 74, 107, 0.08)',
      font: '"M PLUS Rounded 1c", system-ui, sans-serif',
      fontDisplay: '"Noto Serif JP", serif',
    },
  },
  {
    id: 'shrine',
    name: 'Kyoto Shrine',
    tokens: {
      primary: '#c0392b',
      primaryInk: '#fff8f0',
      accent: '#d4a012',
      bg: '#f5f0e6',
      surface: '#fffaf4',
      ink: '#3d2314',
      muted: '#7a5c42',
      line: '#e8d4b8',
      good: '#2d6a4f',
      bad: '#9b2226',
      radius: '0.2rem',
      radiusLg: '0.35rem',
      shadow: '0 3px 14px rgba(61, 35, 20, 0.12)',
      font: '"M PLUS Rounded 1c", sans-serif',
      fontDisplay: '"Yuji Syuku", "Noto Serif JP", serif',
    },
  },
  {
    id: 'atlas',
    name: 'Treasure Atlas',
    tokens: {
      primary: '#5c3d2e',
      primaryInk: '#f4e4bc',
      accent: '#b8860b',
      bg: '#e8d5b0',
      surface: '#f4e4bc',
      ink: '#2c1810',
      muted: '#6b4c35',
      line: '#c4a574',
      good: '#3d5c3a',
      bad: '#8b2500',
      radius: '0.15rem',
      radiusLg: '0.25rem',
      shadow: '2px 3px 8px rgba(44,24,16,0.2)',
      font: '"Libre Baskerville", Georgia, serif',
      fontDisplay: '"Libre Baskerville", Georgia, serif',
    },
  },
  {
    id: 'scrapbook',
    name: 'Sticker Scrapbook',
    tokens: {
      primary: '#ff6b9d',
      primaryInk: '#ffffff',
      accent: '#4ecdc4',
      bg: '#fff8f3',
      surface: '#ffffff',
      ink: '#2d2838',
      muted: '#6e6672',
      line: '#f0e4dc',
      good: '#06d6a0',
      bad: '#ef476f',
      radius: '0.4rem',
      radiusLg: '0.25rem',
      shadow: '3px 4px 0 rgba(45, 40, 56, 0.12)',
      font: '"Caveat", cursive',
      fontDisplay: '"Caveat", cursive',
    },
  },
  {
    id: 'kiyo',
    name: 'Kiyo Precision',
    tokens: {
      primary: '#1d1d1f',
      primaryInk: '#ffffff',
      accent: '#e8a0b8',
      bg: '#f5f5f7',
      surface: '#ffffff',
      ink: '#1d1d1f',
      muted: '#86868b',
      line: '#e8e8ed',
      good: '#34c759',
      bad: '#ff3b30',
      radius: '0.75rem',
      radiusLg: '1.125rem',
      shadow: '0 2px 20px rgba(0,0,0,0.06), 0 0 0 0.5px rgba(0,0,0,0.04)',
      font: '-apple-system, BlinkMacSystemFont, "Inter", "SF Pro Display", sans-serif',
      fontDisplay: '-apple-system, BlinkMacSystemFont, "Inter", sans-serif',
    },
  },
  {
    id: 'liquid',
    name: 'Liquid Glass',
    tokens: {
      primary: '#ffffff',
      primaryInk: '#1a1a2e',
      accent: '#a78bfa',
      bg: '#0a0a12',
      surface: 'rgba(255,255,255,0.12)',
      ink: '#ffffff',
      muted: 'rgba(255,255,255,0.55)',
      line: 'rgba(255,255,255,0.18)',
      good: '#4ade80',
      bad: '#fb7185',
      radius: '1rem',
      radiusLg: '1.25rem',
      shadow: '0 8px 32px rgba(0,0,0,0.2)',
      font: '-apple-system, BlinkMacSystemFont, "Inter", sans-serif',
      fontDisplay: '-apple-system, BlinkMacSystemFont, "Inter", sans-serif',
    },
  },
  {
    id: 'wamon',
    name: 'Wagara Washi',
    tokens: {
      primary: '#b5352d',
      primaryInk: '#fffaf7',
      accent: '#b8956a',
      bg: '#f0ebe3',
      surface: '#faf7f2',
      ink: '#2c2620',
      muted: '#7a6f63',
      line: '#ddd5c8',
      good: '#4a7c59',
      bad: '#9b2d22',
      radius: '0.5rem',
      radiusLg: '0.75rem',
      shadow: '0 2px 14px rgba(44, 38, 32, 0.07)',
      font: '-apple-system, "Inter", "M PLUS Rounded 1c", sans-serif',
      fontDisplay: '"Noto Serif JP", "Libre Baskerville", serif',
    },
  },
  {
    id: 'sumi',
    name: 'Sumi-e Ink',
    tokens: {
      primary: '#e60012',
      primaryInk: '#ffffff',
      accent: '#1a1a1a',
      bg: '#ffffff',
      surface: '#ffffff',
      ink: '#1a1a1a',
      muted: '#888888',
      line: '#e8e8e8',
      good: '#2d6a4f',
      bad: '#c62828',
      radius: '0.35rem',
      radiusLg: '0.5rem',
      shadow: '0 1px 8px rgba(0, 0, 0, 0.04)',
      font: '"Noto Serif JP", "Libre Baskerville", Georgia, serif',
      fontDisplay: '"Noto Serif JP", "Libre Baskerville", serif',
    },
  },
  {
    id: 'kawaii',
    name: 'Mofu Kawaii',
    tokens: {
      primary: '#e8919d',
      primaryInk: '#ffffff',
      accent: '#f5a623',
      bg: '#fdf2f4',
      surface: '#ffffff',
      ink: '#4a3728',
      muted: '#c9a0a8',
      line: '#f5dde2',
      good: '#7bc67e',
      bad: '#e57373',
      radius: '1.1rem',
      radiusLg: '1.35rem',
      shadow: '0 4px 18px rgba(232, 145, 157, 0.14)',
      font: '"M PLUS Rounded 1c", "DM Sans", sans-serif',
      fontDisplay: '"M PLUS Rounded 1c", sans-serif',
    },
  },
  {
    id: 'izakaya',
    name: 'Izakaya Navy',
    tokens: {
      primary: '#e9542e',
      primaryInk: '#2d3277',
      accent: '#ffffff',
      bg: '#2d3277',
      surface: '#e9542e',
      ink: '#ffffff',
      muted: 'rgba(255, 255, 255, 0.65)',
      line: 'rgba(255, 255, 255, 0.15)',
      good: '#7bc67e',
      bad: '#ff6b6b',
      radius: '1rem',
      radiusLg: '1.25rem',
      shadow: '0 6px 24px rgba(0, 0, 0, 0.2)',
      font: '"DM Sans", "Inter", sans-serif',
      fontDisplay: '"DM Sans", sans-serif',
    },
  },
  {
    id: 'zen',
    name: 'Zen Parchment',
    tokens: {
      primary: '#c41e3a',
      primaryInk: '#faf6ef',
      accent: '#1a1a1a',
      bg: '#e5d9c3',
      surface: '#f7f2ea',
      ink: '#1a1a1a',
      muted: '#7a6f5f',
      line: '#d4c4a8',
      good: '#2e7d32',
      bad: '#b71c1c',
      radius: '0.85rem',
      radiusLg: '1.1rem',
      shadow: '0 3px 14px rgba(26, 26, 26, 0.08)',
      font: '"Noto Serif JP", "Yuji Syuku", serif',
      fontDisplay: '"Yuji Syuku", "Noto Serif JP", serif',
    },
  },
] as const;

export const BUILTIN_THEME_MAP = Object.fromEntries(
  BUILTIN_THEME_PRESETS.map((p) => [p.id, p]),
) as Record<BuiltinThemeId, BuiltinThemePreset>;

export const DEFAULT_BUILTIN_THEME_ID: BuiltinThemeId = 'zen';

/** Default enabled set for new events: zen + 5 companions. */
export const DEFAULT_ENABLED_THEME_IDS: BuiltinThemeId[] = [
  'zen',
  'neon',
  'sakura',
  'forest',
  'kiyo',
  'liquid',
];

export const MAX_PLAYER_THEMES = 6;
