/**
 * Writes src/environments/environment.deploy.ts from CI/host env vars.
 * Used by Cloudflare Pages (npm run build:pages). Never commit the output file.
 *
 * Required:
 *   SUPABASE_URL
 *   SUPABASE_PUBLISHABLE_KEY  (or SUPABASE_ANON_KEY)
 *
 * Optional:
 *   BACKEND=supabase
 *   SENTRY_DSN
 *   APP_VERSION
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, '..');
const out = resolve(root, 'src/environments/environment.deploy.ts');

const url = process.env.SUPABASE_URL?.trim();
const key = (
  process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY
)?.trim();
const backend = process.env.BACKEND?.trim() || 'supabase';
const sentryDsn = process.env.SENTRY_DSN?.trim() || '';
const devRef = 'rvtltgrlsmapwonmwsbf';
const deployLabel =
  process.env.DEPLOY_LABEL?.trim() ||
  (url?.includes(devRef) ? 'DEV' : '');

let appVersion = process.env.APP_VERSION?.trim();
if (!appVersion) {
  try {
    appVersion = JSON.parse(readFileSync(resolve(root, 'package.json'), 'utf8')).version;
  } catch {
    appVersion = '0.0.0';
  }
}

if (!url || !key) {
  console.error(
    'build:pages needs SUPABASE_URL and SUPABASE_PUBLISHABLE_KEY (or SUPABASE_ANON_KEY).',
  );
  process.exit(1);
}

if (backend !== 'mock' && backend !== 'supabase') {
  console.error(`BACKEND must be "mock" or "supabase", got "${backend}".`);
  process.exit(1);
}

const contents = `/** Generated by scripts/write-env.mjs — do not edit or commit. */
export const environment = {
  backend: '${backend}' as 'mock' | 'supabase',
  appVersion: '${appVersion}',
  sentryDsn: '${sentryDsn.replace(/'/g, "\\'")}',
  supabaseUrl: '${url.replace(/'/g, "\\'")}',
  supabaseAnonKey: '${key.replace(/'/g, "\\'")}',
  deployLabel: '${deployLabel.replace(/'/g, "\\'")}',
};
`;

writeFileSync(out, contents, 'utf8');
console.log(`Wrote ${out} (backend=${backend}, supabase=${url})`);
